# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Kunal Gupta
tagline:          'Developer'
description:      'Developer'
url:              https://kunall17.github.io
baseurl:          ''# the optional subpath of your site, e.g. "/blog"

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_about"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Custom vars

github:
  repo: https://github.com/kunall17/kunall17.github.io

version:            3.4.1
sidebar_home_link:  true
